# This workflow will deploy a new task definition to Amazon ECS, whenever a new
# container image is pushed from the "develop" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create a repository to store your images.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#
# 4. Store an IAM user access key in GitHub Actions secrets.
#    See the documentation for each action used below for the recommended IAM
#    policies for this IAM user, and best practices on handling the access key
#    credentials.
#
# Refs:
#
# - https://docs.github.com/en/actions/use-cases-and-examples/deploying/deploying-to-amazon-elastic-container-service
# - https://github.com/marketplace/actions/amazon-ecs-deploy-task-definition-action-for-github-actions
# - https://github.com/aws-actions/amazon-ecs-deploy-task-definition
#
# Uso ou não da action 'aws-actions/amazon-ecs-deploy-task-definition':
#
# Para fazer funcionar com o aws-actions/amazon-ecs-deploy-task-definition@v1 a
# gente vai precisar realmente alterar alguma coisa na task definition, que não
# é o caminho que estamos tomando. Estamos mantendo a task intacta, com as tags
# latest/homolog/etc, e somente pedindo a atualização da imagem.
#
# Pra usar essa action a gente precisaria passar, por exemplo, a deployzar uma
# versão específica (versão X.Y.Z).
#
# Estou assumindo que não vamos nesse caminho e vou abandonar, por hora, a
# action aws-actions/amazon-ecs-deploy-task-definition.
#

name: Deploy Frontend to Amazon ECS

on:
  workflow_run:
    workflows:
      - "Docker Build and Push Frontend" # frontend.yml
    # branches: [ "main", "homolog" ]
    branches:
      - "develop"
      - "homolog"
    types:
      - completed

permissions:
  contents: read

jobs:
  check-version:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.result.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for version change
        id: version_check
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - './backend/src/camara_de_curitiba/setup.py'
      - id: result
        run: echo "changed=${{ steps.version_check.outputs.backend }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && needs.check-version.outputs.changed == 'true'

    needs:
      - check-version

    steps:
    - name: Deploy Frontend on Amazon ECS
      run: |
        echo "::debug::Deploy FRONTEND"
